// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV9jechLh-hU-uvxAH4A_KB2333J6xkgM',
    appId: '1:348127732306:web:6778f1c911eb85e4ccf58b',
    messagingSenderId: '348127732306',
    projectId: 'ecdata-eb3b2',
    authDomain: 'ecdata-eb3b2.firebaseapp.com',
    storageBucket: 'ecdata-eb3b2.appspot.com',
    measurementId: 'G-3PLC5ZJ9C7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKvhCtwOSBAwjQ2JYutHSKwjBBkDTRQU4',
    appId: '1:348127732306:android:5dc2e2350dd27ca7ccf58b',
    messagingSenderId: '348127732306',
    projectId: 'ecdata-eb3b2',
    storageBucket: 'ecdata-eb3b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaK-TZn-BZwVXKylQgYp7jt6JH2F5icgM',
    appId: '1:348127732306:ios:33ec605f52ea2c9eccf58b',
    messagingSenderId: '348127732306',
    projectId: 'ecdata-eb3b2',
    storageBucket: 'ecdata-eb3b2.appspot.com',
    androidClientId: '348127732306-hrt675erc5dpeebflk5m6trprdggnlgn.apps.googleusercontent.com',
    iosBundleId: 'com.ndc.ndcdata',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaK-TZn-BZwVXKylQgYp7jt6JH2F5icgM',
    appId: '1:348127732306:ios:33ec605f52ea2c9eccf58b',
    messagingSenderId: '348127732306',
    projectId: 'ecdata-eb3b2',
    storageBucket: 'ecdata-eb3b2.appspot.com',
    androidClientId: '348127732306-hrt675erc5dpeebflk5m6trprdggnlgn.apps.googleusercontent.com',
    iosBundleId: 'com.ndc.ndcdata',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAV9jechLh-hU-uvxAH4A_KB2333J6xkgM',
    appId: '1:348127732306:web:f2a25b2f8ad18398ccf58b',
    messagingSenderId: '348127732306',
    projectId: 'ecdata-eb3b2',
    authDomain: 'ecdata-eb3b2.firebaseapp.com',
    storageBucket: 'ecdata-eb3b2.appspot.com',
    measurementId: 'G-Y9ZGJXSS8S',
  );
}
