// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyBSVeEDy4oZGkqTY7pYWvsJz6Cm-O1HPGo',
//     appId: '1:348127732306:web:0773589960a1656accf58b',
//     messagingSenderId: '348127732306',
//     projectId: 'ecdata-eb3b2',
//     authDomain: 'ecdata-eb3b2.firebaseapp.com',
//     storageBucket: 'ecdata-eb3b2.appspot.com',
//     measurementId: 'G-B5S0V9S45H',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDyIm_8-e8yrWCZjf_5dy6WevtuL9a6Gfk',
//     appId: '1:348127732306:android:7b9d199cea6766c8ccf58b',
//     messagingSenderId: '348127732306',
//     projectId: 'ecdata-eb3b2',
//     storageBucket: 'ecdata-eb3b2.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCaK-TZn-BZwVXKylQgYp7jt6JH2F5icgM',
//     appId: '1:348127732306:ios:49c4b4258c28cf67ccf58b',
//     messagingSenderId: '348127732306',
//     projectId: 'ecdata-eb3b2',
//     storageBucket: 'ecdata-eb3b2.appspot.com',
//     iosBundleId: 'com.ndc.ecdesk',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyCaK-TZn-BZwVXKylQgYp7jt6JH2F5icgM',
//     appId: '1:348127732306:ios:d2e9d878f463b350ccf58b',
//     messagingSenderId: '348127732306',
//     projectId: 'ecdata-eb3b2',
//     storageBucket: 'ecdata-eb3b2.appspot.com',
//     iosBundleId: 'com.ndc.ecdesk.RunnerTests',
//   );
// }
